name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
  actions: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'
      - run: go build -o jira-helper-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: softprops/action-gh-release@v1
        with:
          files: jira-helper-*
